after_success: 
  - "java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml"
before_cache: 
  - "rm -rf $HOME/.m2/repository/com/autentia/traviscodacy"
before_install: 
  - "sudo apt-get install jq"
  - "wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)"
cache: 
  directories: 
  - $HOME/.m2
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml
deploy: 
  - 
    api-key: c399f4fc-b99c-45a9-baae-61dc1c27349f
    app: app-grupoc2c-2019
    provider: heroku
    skip_cleanup: true
    true: develop
dist: trusty
install: 
  - "mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8"
jdk: 
  - oraclejdk8
language: java
notifications: 
  email: 
    on_failure: always
    on_success: never
    recipients: 
      - ggtpi0gabriel@gmail.com
      - sergioluke35@gmail.com
sudo: false
